# Generated by Django 5.2.14 on 2026-05-11 14:18

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('roadmap', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='concept',
            name='examples',
            field=models.JSONField(default=list, help_text='List of example sentences'),
        ),
        migrations.CreateModel(
            name='Exercise',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(choices=[('FILL_BLANK', 'Fill in the Blank'), ('READ_ALOUD', 'Read Aloud'), ('WRITING', 'Sentence Writing')], max_length=20)),
                ('question', models.TextField()),
                ('correct_answer', models.TextField(blank=True, null=True)),
                ('hint', models.CharField(blank=True, max_length=200, null=True)),
                ('options', models.JSONField(blank=True, default=list, help_text='For Fill in the Blank choices', null=True)),
                ('concept', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='exercises', to='roadmap.concept')),
            ],
        ),
        migrations.CreateModel(
            name='UserConceptProgress',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_completed', models.BooleanField(default=False)),
                ('score', models.IntegerField(default=0)),
                ('last_practiced', models.DateTimeField(auto_now=True)),
                ('concept', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='roadmap.concept')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'unique_together': {('user', 'concept')},
            },
        ),
    ]
