# Generated by Django 5.2.14 on 2026-05-12 01:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('roadmap', '0002_concept_examples_exercise_userconceptprogress'),
    ]

    operations = [
        migrations.AddField(
            model_name='exercise',
            name='explanation',
            field=models.TextField(blank=True, null=True),
        ),
    ]
