# Generated by Django 5.2.14 on 2026-05-12 02:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('roadmap', '0003_exercise_explanation'),
    ]

    operations = [
        migrations.AddField(
            model_name='concept',
            name='common_mistakes',
            field=models.JSONField(default=list, help_text="[{'wrong': '...', 'right': '...', 'why': '...'}]"),
        ),
        migrations.AddField(
            model_name='concept',
            name='formula',
            field=models.CharField(blank=True, help_text='Grammar Formula (e.g. S+V+O)', max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='concept',
            name='grammar_rules',
            field=models.TextField(blank=True, help_text='Key rules for this concept', null=True),
        ),
        migrations.AlterField(
            model_name='concept',
            name='content',
            field=models.TextField(help_text='Detailed explanation of the concept'),
        ),
        migrations.AlterField(
            model_name='concept',
            name='examples',
            field=models.JSONField(default=list, help_text="[{'en': '...', 'te': '...', 'explanation': '...'}]"),
        ),
    ]
