# Generated by Django 5.2.14 on 2026-05-14 18:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('roadmap', '0004_concept_common_mistakes_concept_formula_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='exercise',
            name='category',
            field=models.CharField(default='General', max_length=50),
        ),
        migrations.AddField(
            model_name='exercise',
            name='difficulty',
            field=models.CharField(default='Beginner', max_length=20),
        ),
        migrations.AddField(
            model_name='exercise',
            name='telugu_meaning',
            field=models.TextField(blank=True, null=True),
        ),
    ]
