CORE_HR_QUESTIONS = [
    {"q": "Tell me about yourself.", "a": "Give a brief overview of your professional background, key achievements, and why you are a good fit for this specific role."},
    {"q": "Why do you want to join our company?", "a": "Show that you've researched the company. Mention their values, products, or recent news that genuinely excites you."},
    {"q": "What are your greatest strengths and weaknesses?", "a": "For strengths, focus on skills relevant to the job. For weaknesses, pick a real but minor one and explain how you are working to improve it."},
    {"q": "Where do you see yourself in five years?", "a": "Talk about your career goals and how this role fits into your long-term plans for professional growth."},
    {"q": "Tell me about a time you handled a conflict at work.", "a": "Use the STAR method (Situation, Task, Action, Result) to describe how you resolved a professional disagreement."},
    {"q": "What is your greatest professional achievement?", "a": "Focus on a specific, measurable success that demonstrates your skills and value to a company."},
    {"q": "Why should we hire you over other candidates?", "a": "Summarize your unique combination of skills, experience, and passion that makes you the perfect fit."},
    {"q": "How do you handle pressure or stressful situations?", "a": "Explain your techniques for staying calm, organized, and focused when faced with tight deadlines or challenges."},
    {"q": "What are your salary expectations?", "a": "Provide a range based on market research for the role and location, or express flexibility based on the total compensation package."},
    {"q": "Do you have any questions for us?", "a": "Always have 2-3 thoughtful questions about the team, company culture, or the specific challenges of the role."}
]

INTERVIEW_QUESTIONS = {
    'Frontend Developer': [
        {"q": "What is the difference between let, const, and var?", "a": "'var' is function-scoped and can be re-declared. 'let' and 'const' are block-scoped. 'const' cannot be reassigned, while 'let' can. 'let' and 'const' also avoid hoisting issues."},
        {"q": "Explain the box model in CSS.", "a": "The CSS box model consists of margins, borders, padding, and the actual content. It defines how the size of an element is calculated and how it interacts with other elements."},
        {"q": "How does React's Virtual DOM work?", "a": "React keeps a copy of the real DOM. When state changes, it calculates the difference (diffing) and updates only the necessary parts in the real DOM (reconciliation) for better performance."},
        {"q": "What is Hoisting in JavaScript?", "a": "Hoisting is JS's behavior of moving declarations to the top of their scope. 'var' is hoisted with 'undefined', whereas 'let' and 'const' are hoisted but remain in a temporal dead zone."},
        {"q": "Explain the difference between synchronous and asynchronous code.", "a": "Synchronous code runs sequentially, blocking execution until a task is done. Asynchronous code (using Promises/async-await) allows tasks to run in the background without blocking the main thread."},
        {"q": "What are the new features in ES6?", "a": "Key ES6 features include Arrow functions, Template literals, Destructuring, Modules, Classes, and the Let/Const keywords."},
        {"q": "How do you optimize a website's performance?", "a": "Optimization includes minifying CSS/JS, lazy loading images, using CDNs, implementing caching, and reducing the number of HTTP requests."},
        {"q": "What is the use of 'this' keyword in JavaScript?", "a": "The 'this' keyword refers to the object it belongs to. Its value depends on how the function is called (global, object method, or constructor)."},
        {"q": "Explain Flexbox and CSS Grid.", "a": "Flexbox is designed for one-dimensional layouts (rows OR columns), while CSS Grid is designed for two-dimensional layouts (rows AND columns) simultaneously."},
        {"q": "What are Higher-Order Components in React?", "a": "An HOC is a function that takes a component and returns a new component with added functionality or data."},
        {"q": "How do you handle state management in a large application?", "a": "For large apps, we use libraries like Redux, MobX, or React Context API to manage a global state accessible across multiple components."},
        {"q": "What is the difference between == and ===?", "a": "== performs type coercion (converts types to match), while === checks for both value and type equality (strict equality)."},
        {"q": "Explain the concept of 'Closures' in JavaScript.", "a": "A closure is a function that remembers the environment in which it was created, allowing it to access variables from an outer function even after that function has finished execution."},
        {"q": "What is the purpose of the 'alt' attribute on images?", "a": "The 'alt' attribute provides alternative text for screen readers and displays if the image fails to load, improving accessibility and SEO."},
        {"q": "How do you make a website responsive?", "a": "Responsive design uses Fluid grids, Flexible images, and CSS Media Queries to adapt the layout to different screen sizes."},
        {"q": "What is the difference between LocalStorage and SessionStorage?", "a": "LocalStorage persists even after the browser is closed, whereas SessionStorage is cleared when the page session ends (tab is closed)."},
        {"q": "Explain the use of 'Promises' and 'Async/Await'.", "a": "Promises represent a value that will be available in the future. Async/Await is syntactical sugar over Promises that makes asynchronous code look and behave more like synchronous code."},
        {"q": "What is a CSS preprocessor and which ones have you used?", "a": "Preprocessors like Sass or Less allow you to use variables, nesting, and mixins in CSS, which are then compiled into standard CSS."},
        {"q": "How do you handle cross-browser compatibility issues?", "a": "We use CSS resets, vendor prefixes, polyfills for JS, and test the site on multiple browsers/devices using tools like BrowserStack."},
        {"q": "What is the 'Shadow DOM'?", "a": "Shadow DOM allows a component to have its own 'hidden' DOM tree that can't be accidentally accessed from the main document, ensuring style and logic encapsulation."}
    ],
    'Backend Developer': [
        {"q": "What is the difference between SQL and NoSQL databases?", "a": "SQL databases are relational and table-based with fixed schemas. NoSQL databases are non-relational, document or key-value based, and allow flexible schemas for unstructured data."},
        {"q": "Explain the concept of RESTful APIs.", "a": "REST (Representational State Transfer) uses standard HTTP methods (GET, POST, PUT, DELETE) and status codes to interact with resources over a network in a stateless manner."},
        {"q": "How does indexing improve database performance?", "a": "Indexing creates a data structure that allows the database to find rows much faster without scanning every single record, similar to an index in a book."},
        {"q": "What is a Middleware in the context of backend frameworks?", "a": "Middleware is a function that sits between the request and response, used for tasks like logging, authentication, and error handling."},
        {"q": "Explain the difference between authentication and authorization.", "a": "Authentication verifies WHO a user is (login), while Authorization determines WHAT they are allowed to do (permissions)."},
        {"q": "What is the purpose of an ORM?", "a": "An Object-Relational Mapper (ORM) allows developers to interact with a database using their programming language's objects instead of writing raw SQL queries."},
        {"q": "How do you handle error handling in a distributed system?", "a": "In distributed systems, we use centralized logging, standardized error codes, retries with exponential backoff, and circuit breakers to prevent cascading failures."},
        {"q": "What is the difference between a process and a thread?", "a": "A process is an independent program execution with its own memory. A thread is a subset of a process that shares memory with other threads in the same process."},
        {"q": "Explain the concept of 'Dependency Injection'.", "a": "Dependency Injection is a design pattern where an object's dependencies are provided to it (usually via constructor) rather than the object creating them itself, improving testability."},
        {"q": "How do you secure an API?", "a": "Security measures include using HTTPS, API keys, JWT tokens for sessions, rate limiting, and input validation to prevent injection attacks."},
        {"q": "What is a 'Race Condition'?", "a": "A race condition occurs when multiple threads or processes try to change shared data at the same time, leading to unpredictable results depending on the order of execution."},
        {"q": "Explain the difference between horizontal and vertical scaling.", "a": "Vertical scaling means adding more power (CPU/RAM) to an existing server. Horizontal scaling means adding more servers to handle the load."},
        {"q": "What are 'WebSockets' and when would you use them?", "a": "WebSockets provide a full-duplex communication channel over a single TCP connection, ideal for real-time apps like chat or live notifications."},
        {"q": "How do you optimize a slow database query?", "a": "Optimization includes using EXPLAIN to analyze the query, adding missing indexes, avoiding SELECT *, and caching frequent results."},
        {"q": "What is 'Caching' and what are the common strategies?", "a": "Caching stores frequently accessed data in memory (like Redis). Common strategies include Cache-Aside, Write-Through, and Write-Back."},
        {"q": "Explain the 'Microservices' architecture.", "a": "Microservices break a large application into small, independent services that communicate via APIs, allowing for easier scaling and deployment of individual components."},
        {"q": "What is a 'Load Balancer'?", "a": "A load balancer distributes incoming network traffic across multiple servers to ensure no single server becomes overwhelmed and to provide high availability."},
        {"q": "How do you handle database migrations?", "a": "Migrations are version control for databases, allowing you to update the schema (tables/columns) safely using scripts that can be applied or rolled back."},
        {"q": "What is 'ACID' in the context of databases?", "a": "ACID stands for Atomicity, Consistency, Isolation, and Durability. These properties ensure that database transactions are processed reliably and accurately."},
        {"q": "Explain the use of 'Docker' in backend development.", "a": "Docker packages an application and its dependencies into a container, ensuring it runs exactly the same way in development, testing, and production environments."}
    ],
    'Full Stack Developer': [
        {"q": "Explain the complete flow of a web request from client to server and back.", "a": "The client sends an HTTP request via DNS to the server. The server processes it (middleware, controllers, DB), and sends back an HTTP response (JSON/HTML) which the browser then renders."},
        {"q": "What are the advantages and disadvantages of using a Single Page Application (SPA)?", "a": "Advantages: Faster transitions, better UX. Disadvantages: Slower initial load, SEO challenges (though solvable with SSR)."},
        {"q": "How do you choose between a relational and a non-relational database for a project?", "a": "Use relational (SQL) for structured data with complex relationships. Use non-relational (NoSQL) for high-velocity, unstructured data or when rapid scaling is required."},
        {"q": "Explain the concept of 'CORS' and how to handle it.", "a": "Cross-Origin Resource Sharing is a security feature that blocks requests from different domains. It is handled by setting specific headers on the server to allow trusted origins."},
        {"q": "What is 'Server-Side Rendering' (SSR) vs 'Client-Side Rendering' (CSR)?", "a": "SSR renders the page on the server and sends HTML to the client (better SEO). CSR sends a blank page and JS, which then builds the UI in the browser (faster interactions after load)."},
        {"q": "How do you ensure the security of a full stack application?", "a": "Security involves HTTPS, securing sessions with JWT/Cookies, sanitizing inputs, using CSRF tokens, and keeping dependencies updated."},
        {"q": "What is 'GitFlow' and how do you use it for version control?", "a": "GitFlow is a branching model that uses 'master' for production, 'develop' for integration, and 'feature' branches for individual tasks."},
        {"q": "Explain the difference between 'Monolithic' and 'Microservices' architectures.", "a": "Monolithic is one single codebase for everything. Microservices are independent services working together. Monolith is easier to start, Microservices are easier to scale."},
        {"q": "How do you handle state synchronization between frontend and backend?", "a": "Synchronization is managed through APIs (REST/GraphQL), WebSockets for real-time updates, and frontend state management (Redux) to keep the UI in sync with server data."},
        {"q": "What is 'CI/CD' and why is it important?", "a": "Continuous Integration and Continuous Deployment automate testing and delivery, ensuring that code changes are integrated and deployed quickly and reliably."},
        {"q": "Explain the use of 'JWT' for session management.", "a": "JSON Web Tokens are used for stateless authentication. The server signs a token and sends it to the client, which includes it in subsequent requests to verify identity."},
        {"q": "How do you optimize both frontend and backend performance?", "a": "Frontend: Minification, lazy loading. Backend: Query optimization, caching, using efficient data structures and algorithms."},
        {"q": "What is 'GraphQL' and how does it differ from REST?", "a": "GraphQL allows clients to request exactly the data they need in a single request, preventing over-fetching or under-fetching which often happens in REST."},
        {"q": "Explain the concept of 'Containerization'.", "a": "Containerization (like Docker) bundles an app with its environment, ensuring it runs consistently across different machines without dependency conflicts."},
        {"q": "How do you manage environment variables in a full stack project?", "a": "We use .env files (not committed to Git) and secret management services in production to keep API keys and passwords secure."},
        {"q": "What is 'Test-Driven Development' (TDD)?", "a": "TDD is a process where you write a failing test first, then write the minimum code to make it pass, and finally refactor the code for better quality."},
        {"q": "Explain the 'MVC' pattern.", "a": "Model-View-Controller separates the app into data (Model), UI (View), and logic (Controller), making the codebase easier to maintain and test."},
        {"q": "How do you handle file uploads in a web application?", "a": "File uploads involve a multipart/form-data request. The server saves the file to storage (like S3) and stores the file URL in the database."},
        {"q": "What are 'Service Workers'?", "a": "Service Workers are scripts that run in the browser background, enabling features like offline support, push notifications, and asset caching for PWAs."},
        {"q": "Explain the role of a 'Message Queue' like RabbitMQ or Kafka.", "a": "Message queues allow for asynchronous communication between services. One service sends a task to the queue, and another service processes it later, improving system responsiveness."}
    ],
    'Mobile App Developer': [
        {"q": "What is the difference between native and cross-platform mobile development?", "a": "Native development uses platform-specific languages (Swift for iOS, Kotlin for Android). Cross-platform uses one codebase (Flutter/React Native) for both, saving time but sometimes sacrificing performance."},
        {"q": "Explain the mobile app lifecycle.", "a": "The lifecycle includes states like Created, Started, Resumed (Active), Paused, Stopped, and Destroyed. Developers must handle data saving and resource management during these transitions."},
        {"q": "How do you handle different screen sizes and resolutions?", "a": "We use flexible layouts (ConstraintLayout in Android, Auto Layout in iOS) and vector graphics (SVG/PDF) to ensure the UI looks good on all devices."},
        {"q": "What is the purpose of an 'Activity' in Android or a 'ViewController' in iOS?", "a": "These are the fundamental building blocks representing a single screen in an app. they manage the UI and the user interactions for that specific screen."},
        {"q": "How do you manage local data storage in a mobile app?", "a": "Common methods include SharedPreferences/UserDefaults for small data, SQLite or Realm for structured data, and local file storage for media."},
        {"q": "Explain the concept of 'Push Notifications'.", "a": "Push notifications are messages sent from a server to a user's device even when the app is not active, used to re-engage users or provide important updates."},
        {"q": "How do you handle background tasks in a mobile application?", "a": "We use WorkManager (Android) or Background Tasks (iOS) to perform long-running operations like syncing data or downloading files without blocking the UI."},
        {"q": "What is 'Deep Linking'?", "a": "Deep linking allows a URL to open a specific screen inside a mobile app instead of just opening the app's home screen or a website."},
        {"q": "How do you optimize the performance and battery usage of a mobile app?", "a": "Optimization involves reducing network calls, optimizing image sizes, avoiding memory leaks, and using efficient background processing."},
        {"q": "Explain the use of 'APIs' in mobile development.", "a": "APIs allow mobile apps to communicate with backend servers to fetch data, authenticate users, and sync information across devices."},
        {"q": "What is the difference between 'Stateful' and 'Stateless' widgets in Flutter?", "a": "Stateless widgets are immutable and don't change. Stateful widgets can change their appearance over time based on user interactions or data updates."},
        {"q": "How do you handle offline mode in a mobile app?", "a": "Offline mode is handled by caching data locally using a database and syncing it with the server once the connection is restored."},
        {"q": "What is 'App Store Optimization' (ASO)?", "a": "ASO is the process of improving an app's visibility in the App Store or Play Store using keywords, better descriptions, and high-quality screenshots."},
        {"q": "Explain the process of publishing an app to the stores.", "a": "The process involves creating a developer account, preparing assets, building a signed release version, and submitting it for review by Apple or Google."},
        {"q": "How do you handle user authentication in mobile apps?", "a": "Common methods include OAuth, Firebase Authentication, or custom JWT-based authentication via a backend API."},
        {"q": "What is 'Reactive Programming' in the context of mobile development?", "a": "Reactive programming (like RxJava or Combine) uses asynchronous data streams to handle UI updates automatically as data changes."},
        {"q": "Explain the use of 'CocoaPods' or 'Gradle'.", "a": "These are dependency managers. CocoaPods is used for iOS projects to manage libraries, while Gradle is used for Android to manage builds and dependencies."},
        {"q": "How do you handle memory management in mobile apps?", "a": "We use Automatic Reference Counting (ARC) in iOS and Garbage Collection in Android. Developers must still be careful to avoid retain cycles and memory leaks."},
        {"q": "What is 'Unit Testing' for mobile applications?", "a": "Unit tests verify that individual components or functions of the app work correctly in isolation, ensuring code reliability and easier maintenance."},
        {"q": "Explain the concept of 'Material Design' and 'Human Interface Guidelines'.", "a": "Material Design (Google) and HIG (Apple) are design systems that provide standards for how apps should look and behave on their respective platforms."}
    ],
    'Data Scientist / AI Engineer': [
        {"q": "What is the difference between Supervised and Unsupervised Learning?", "a": "Supervised learning uses labeled data (input-output pairs) to train models. Unsupervised learning finds patterns and structures in unlabeled data (e.g., clustering)."},
        {"q": "Explain the concept of 'Overfitting' and how to prevent it.", "a": "Overfitting happens when a model learns the noise in training data too well, failing on new data. It can be prevented using regularization, cross-validation, and more data."},
        {"q": "What is a 'Confusion Matrix'?", "a": "A confusion matrix is a table used to evaluate the performance of a classification model, showing True Positives, True Negatives, False Positives, and False Negatives."},
        {"q": "How do you handle missing or outlier data in a dataset?", "a": "Missing data can be handled by imputation or removal. Outliers can be handled by transformation, capping, or using robust algorithms that are less sensitive to them."},
        {"q": "Explain the 'Bias-Variance Tradeoff'.", "a": "Bias is error from overly simple models (underfitting). Variance is error from overly complex models (overfitting). The goal is to find a balance that minimizes total error."},
        {"q": "What is 'Feature Engineering'?", "a": "Feature engineering is the process of creating new features or transforming existing ones to improve the performance of a machine learning model."},
        {"q": "How does a 'Random Forest' algorithm work?", "a": "Random Forest is an ensemble method that combines multiple decision trees. Each tree gives a prediction, and the final result is determined by majority vote or averaging."},
        {"q": "Explain the difference between L1 and L2 regularization.", "a": "L1 (Lasso) can shrink coefficients to zero, performing feature selection. L2 (Ridge) shrinks coefficients but keeps them non-zero, preventing large weights."},
        {"q": "What is 'Gradient Descent'?", "a": "Gradient descent is an optimization algorithm used to minimize the loss function of a model by iteratively moving towards the steepest descent."},
        {"q": "How do you evaluate the performance of a classification model?", "a": "Evaluation metrics include Accuracy, Precision, Recall, F1-Score, and the Area Under the ROC Curve (AUC)."},
        {"q": "What is 'Natural Language Processing' (NLP)?", "a": "NLP is a branch of AI that enables computers to understand, interpret, and generate human language, used in chatbots, translation, and sentiment analysis."},
        {"q": "Explain the concept of 'Deep Learning'.", "a": "Deep Learning is a subset of machine learning based on artificial neural networks with many layers, capable of learning complex patterns from large amounts of data."},
        {"q": "What is a 'Neural Network'?", "a": "A neural network is a series of algorithms that try to recognize underlying relationships in a set of data through a process that mimics the way the human brain operates."},
        {"q": "How do you handle imbalanced datasets?", "a": "Imbalanced data can be handled by oversampling the minority class (SMOTE), undersampling the majority class, or using specialized loss functions."},
        {"q": "What is 'Dimensionality Reduction' and why is it used?", "a": "It's the process of reducing the number of variables in a dataset (e.g., PCA) to simplify the model, reduce noise, and speed up training."},
        {"q": "Explain 'Principal Component Analysis' (PCA).", "a": "PCA is a technique that transforms high-dimensional data into a smaller number of uncorrelated variables (principal components) while retaining most of the variance."},
        {"q": "What are 'Hyperparameters' and how do you tune them?", "a": "Hyperparameters are settings that aren't learned from data (like learning rate). They are tuned using techniques like Grid Search, Random Search, or Bayesian Optimization."},
        {"q": "Explain the difference between 'Batch' and 'Stochastic' Gradient Descent.", "a": "Batch GD uses the entire dataset to update weights. Stochastic GD uses only one sample at a time, making it faster but more erratic."},
        {"q": "What is 'Reinforcement Learning'?", "a": "Reinforcement learning is a type of machine learning where an agent learns to make decisions by performing actions in an environment to maximize a reward."},
        {"q": "How do you deploy a machine learning model into production?", "a": "Deployment involves saving the model (e.g., as a pickle file), creating an API to serve it, and monitoring its performance in a real-world environment."}
    ],
    'Cloud Engineer': [
        {"q": "What are the differences between IaaS, PaaS, and SaaS?", "a": "IaaS provides raw infrastructure (AWS EC2). PaaS provides a platform to build apps (Heroku). SaaS provides ready-to-use software (Gmail)."},
        {"q": "Explain the concept of 'Serverless' computing.", "a": "Serverless allows developers to build and run apps without managing infrastructure. The cloud provider automatically handles scaling and server maintenance (e.g., AWS Lambda)."},
        {"q": "What is 'Auto-scaling' and why is it important?", "a": "Auto-scaling automatically adjusts the number of computing resources based on traffic demand, ensuring performance during peaks and saving costs during low usage."},
        {"q": "How do you ensure high availability in a cloud environment?", "a": "High availability is achieved by deploying resources across multiple Availability Zones (AZs) and using load balancers to distribute traffic."},
        {"q": "What is a 'Virtual Private Cloud' (VPC)?", "a": "A VPC is a private, isolated section of a public cloud where you can launch resources in a virtual network that you define."},
        {"q": "Explain the concept of 'Cloud Storage' (e.g., S3).", "a": "Cloud storage allows you to store and retrieve any amount of data (objects) over the internet, providing high durability and scalability."},
        {"q": "How do you manage security and identity in the cloud (IAM)?", "a": "Identity and Access Management (IAM) allows you to control who can access which cloud resources and what actions they can perform."},
        {"q": "What is 'Infrastructure as Code' (IaC)?", "a": "IaC is the process of managing and provisioning infrastructure through machine-readable definition files (like Terraform) instead of manual configuration."},
        {"q": "Explain the 'Shared Responsibility Model' in cloud computing.", "a": "The cloud provider is responsible for the security OF the cloud (hardware), while the customer is responsible for security IN the cloud (data and apps)."},
        {"q": "What is a 'Content Delivery Network' (CDN)?", "a": "A CDN is a network of distributed servers that deliver web content to users based on their geographic location to reduce latency and speed up load times."},
        {"q": "How do you monitor cloud resources and performance?", "a": "We use monitoring tools (like CloudWatch) to track metrics, logs, and set alarms for any performance issues or resource limits."},
        {"q": "What is 'Multi-cloud' and 'Hybrid Cloud'?", "a": "Multi-cloud uses multiple cloud providers. Hybrid cloud combines private (on-premises) infrastructure with a public cloud."},
        {"q": "Explain the concept of 'Disaster Recovery' in the cloud.", "a": "Disaster recovery involves backing up data and having a plan to restore services quickly in another region if a major outage occurs."},
        {"q": "What are 'Containers' and 'Kubernetes'?", "a": "Containers package apps with their dependencies. Kubernetes is an orchestration platform that manages and scales these containers across a cluster of servers."},
        {"q": "How do you optimize cloud costs?", "a": "Cost optimization involves using reserved instances, deleting unused resources, and right-sizing instances based on actual usage patterns."},
        {"q": "What is a 'Cloud-native' application?", "a": "A cloud-native app is designed specifically to take advantage of cloud features like microservices, containers, and automated management."},
        {"q": "Explain 'Microservices' in a cloud context.", "a": "Microservices in the cloud allow each part of an app to be scaled and managed independently using serverless or containerized environments."},
        {"q": "How do you handle data migration to the cloud?", "a": "Data migration is handled using tools like AWS Snowball or Database Migration Service (DMS) to move large amounts of data securely and quickly."},
        {"q": "What is 'Edge Computing'?", "a": "Edge computing processes data closer to where it is generated (near the user) to reduce latency and bandwidth usage for real-time applications."},
        {"q": "Explain the use of 'API Gateways' in the cloud.", "a": "An API Gateway acts as a front door for APIs, handling tasks like authentication, rate limiting, and request routing to backend services."}
    ],
    'Cybersecurity Analyst': [
        {"q": "What is the 'CIA Triad'?", "a": "The CIA Triad stands for Confidentiality (privacy), Integrity (accuracy), and Availability (accessibility) of data."},
        {"q": "Explain the difference between 'Symmetric' and 'Asymmetric' encryption.", "a": "Symmetric uses the same key for encryption and decryption. Asymmetric uses a public key to encrypt and a private key to decrypt."},
        {"q": "What is a 'Firewall' and how does it work?", "a": "A firewall is a network security device that monitors and filters incoming and outgoing network traffic based on an organization's previously established security policies."},
        {"q": "Explain 'Phishing' and how to prevent it.", "a": "Phishing is a fraudulent attempt to obtain sensitive information by disguising as a trustworthy entity. Prevention includes user training and multi-factor authentication."},
        {"q": "What is 'Two-Factor Authentication' (2FA)?", "a": "2FA adds an extra layer of security by requiring not only a password but also a second piece of information (like a code from an app)."},
        {"q": "Explain the concept of 'SQL Injection'.", "a": "SQL Injection is an attack where malicious SQL statements are inserted into an entry field for execution, potentially allowing access to the database."},
        {"q": "What is 'Cross-Site Scripting' (XSS)?", "a": "XSS is an attack where malicious scripts are injected into trusted websites, which then run in the user's browser to steal cookies or session info."},
        {"q": "How do you perform a 'Risk Assessment'?", "a": "Risk assessment involves identifying assets, threats, and vulnerabilities, and then determining the impact and likelihood of a security incident."},
        {"q": "What is a 'Vulnerability Scanner'?", "a": "A vulnerability scanner is a tool that automatically probes a network or system for known security weaknesses."},
        {"q": "Explain 'Incident Response'.", "a": "Incident response is a set of procedures followed to detect, contain, and recover from a security breach or cyberattack."},
        {"q": "What is 'Malware' and what are the common types?", "a": "Malware is malicious software designed to damage or gain unauthorized access. Types include viruses, worms, ransomware, and spyware."},
        {"q": "Explain 'Social Engineering'.", "a": "Social engineering is the psychological manipulation of people into performing actions or divulging confidential information."},
        {"q": "What is 'Network Sniffing'?", "a": "Network sniffing is the process of intercepting and logging traffic that passes over a digital network using a packet sniffer tool."},
        {"q": "How do you secure a wireless network?", "a": "Securing a Wi-Fi network includes using WPA3 encryption, changing default passwords, and disabling SSID broadcasting if necessary."},
        {"q": "What is a 'VPN'?", "a": "A Virtual Private Network creates a secure, encrypted tunnel between a user's device and the internet, protecting their data and identity."},
        {"q": "Explain 'Encryption at Rest' vs 'Encryption in Transit'.", "a": "Encryption at rest protects data stored on disks. Encryption in transit protects data as it moves over the network."},
        {"q": "What is 'Penetration Testing'?", "a": "Penetration testing (ethical hacking) is an authorized simulated cyberattack on a computer system, performed to evaluate the security of the system."},
        {"q": "How do you handle a data breach?", "a": "Handling a breach involves containing the threat, assessing the damage, notifying affected parties, and improving security to prevent future incidents."},
        {"q": "What is 'Zero Trust' architecture?", "a": "Zero Trust is a security model that requires strict identity verification for every person and device trying to access resources, regardless of whether they are inside or outside the network."},
        {"q": "Explain 'SIEM'.", "a": "Security Information and Event Management (SIEM) provides real-time analysis of security alerts generated by applications and network hardware."}
    ],
    'Mainframe Developer': [
        {"q": "What is a 'Mainframe' and what are its key characteristics?", "a": "A mainframe is a high-performance computer used for large-scale computing. Key characteristics include high availability, security, and massive throughput for transaction processing."},
        {"q": "Explain 'COBOL' and its role in mainframe development.", "a": "COBOL is a high-level programming language designed for business and administrative use, widely used on mainframes for critical banking and insurance systems."},
        {"q": "What is 'JCL'?", "a": "Job Control Language (JCL) is used on IBM mainframes to instruct the system on how to run a batch job or start a subsystem."},
        {"q": "Explain 'VSAM'.", "a": "Virtual Storage Access Method (VSAM) is an IBM file storage system that provides high-performance access to data in various formats like keyed or sequential."},
        {"q": "What is 'CICS'?", "a": "Customer Information Control System (CICS) is a transaction server that allows mainframes to run high-volume online applications for thousands of users simultaneously."},
        {"q": "How does 'DB2' work on a mainframe?", "a": "DB2 is a relational database management system (RDBMS) that provides efficient data management and high availability for mainframe applications."},
        {"q": "What is 'TSO/ISPF'?", "a": "Time Sharing Option (TSO) allows users to interact with the mainframe. ISPF is a panel-driven interface used for editing files and managing jobs."},
        {"q": "Explain the concept of 'Batch Processing' on a mainframe.", "a": "Batch processing involves running large volumes of data through a series of programs without manual intervention, usually during off-peak hours."},
        {"q": "What is a 'Partitioned Data Set' (PDS)?", "a": "A PDS is a data set that contains multiple members, each of which can hold a separate program or piece of data, similar to a folder on a PC."},
        {"q": "How do you debug a mainframe program?", "a": "Debugging tools like IBM Debug for z/OS or using display statements and analyzing core dumps are used to find and fix errors in mainframe code."},
        {"q": "What is 'MVS'?", "a": "Multiple Virtual Storage (MVS) is the primary operating system for IBM mainframes, providing memory isolation and multitasking capabilities."},
        {"q": "Explain the role of 'Z/OS'.", "a": "Z/OS is the modern, secure, and reliable 64-bit operating system for IBM Z mainframes, supporting both traditional and modern workloads."},
        {"q": "What is a 'Copybook' in COBOL?", "a": "A copybook is a file containing standard data structures or code segments that can be included in multiple COBOL programs to ensure consistency."},
        {"q": "How do you handle file processing in JCL?", "a": "File processing in JCL is handled using DD (Data Definition) statements that link logical files in the program to physical datasets on the system."},
        {"q": "What is 'Mainframe Modernization'?", "a": "Modernization involves updating legacy mainframe systems to work with modern technologies like cloud, APIs, and mobile applications."},
        {"q": "Explain 'RACF'.", "a": "Resource Access Control Facility (RACF) is the security manager for IBM mainframes, controlling user access to files, programs, and other resources."},
        {"q": "What is a 'Stored Procedure' in DB2?", "a": "A stored procedure is a block of code stored in the database that can be called by applications to perform complex data operations efficiently."},
        {"q": "How do you optimize mainframe performance?", "a": "Optimization involves efficient coding, reducing I/O operations, using proper indexing in DB2, and managing system resources effectively."},
        {"q": "What is 'MQ Series' on a mainframe?", "a": "IBM MQ is message-oriented middleware that allows mainframe applications to communicate with other systems reliably and asynchronously."},
        {"q": "Explain the process of 'IPL'.", "a": "Initial Program Load (IPL) is the process of loading the operating system into the mainframe's memory to start the system, similar to 'booting' a PC."}
    ],
    'QA Engineer / Tester': [
        {"q": "What is the difference between Manual and Automated testing?", "a": "Manual testing is performed by humans step-by-step. Automated testing uses scripts and tools to execute test cases automatically, saving time for repetitive tasks."},
        {"q": "Explain the 'Software Testing Life Cycle' (STLC).", "a": "STLC includes phases like Requirement Analysis, Test Planning, Test Design, Environment Setup, Test Execution, and Test Closure."},
        {"q": "What is 'Regression Testing'?", "a": "Regression testing ensures that new code changes haven't broken existing functionality in the application."},
        {"q": "How do you write a 'Test Case'?", "a": "A test case includes a Title, Pre-conditions, Steps, Test Data, Expected Result, and Actual Result."},
        {"q": "What is 'Smoke Testing' vs 'Sanity Testing'?", "a": "Smoke testing verifies if the critical features of a build work. Sanity testing checks specific functionality after a bug fix or code change."},
        {"q": "Explain 'Black Box', 'White Box', and 'Grey Box' testing.", "a": "Black Box: No internal knowledge of code. White Box: Full knowledge of code. Grey Box: Partial knowledge of internal structures."},
        {"q": "What is 'Unit Testing'?", "a": "Unit testing is the process of testing individual components or modules of an application in isolation, usually done by developers."},
        {"q": "How do you handle bug reporting and tracking?", "a": "Bugs are reported using tools like Jira, including details like severity, priority, steps to reproduce, and screenshots."},
        {"q": "What is 'Equivalence Partitioning' and 'Boundary Value Analysis'?", "a": "Equivalence Partitioning groups inputs into valid/invalid sets. BVA tests the values at the boundaries of these sets where bugs often hide."},
        {"q": "Explain 'User Acceptance Testing' (UAT).", "a": "UAT is the final phase where the end users test the software in a real-world environment to ensure it meets their requirements."},
        {"q": "What is 'Load Testing' and 'Stress Testing'?", "a": "Load testing checks how the system behaves under expected usage. Stress testing pushes the system beyond its limits to see how it fails."},
        {"q": "How do you choose which test cases to automate?", "a": "Automate repetitive, high-risk, and stable test cases. Avoid automating one-time tests or frequently changing features."},
        {"q": "What are the common testing tools you have used?", "a": "Common tools include Selenium for web, Appium for mobile, Postman for APIs, and JUnit/TestNG for unit tests."},
        {"q": "Explain the 'Agile' testing methodology.", "a": "In Agile, testing is integrated into the development process. Testers work alongside developers in short sprints to ensure quality from the start."},
        {"q": "What is 'Continuous Testing'?", "a": "Continuous testing is the process of executing automated tests as part of the software delivery pipeline (CI/CD) to provide immediate feedback."},
        {"q": "How do you perform 'API Testing'?", "a": "API testing involves sending requests (GET/POST) to endpoints and validating the status codes, headers, and response body (JSON/XML)."},
        {"q": "What is 'Mobile App Testing'?", "a": "Mobile testing involves checking the app's functionality, usability, and performance on different devices and operating systems."},
        {"q": "Explain 'Security Testing'.", "a": "Security testing identifies vulnerabilities like SQL injection and XSS to ensure the application's data and resources are protected from attacks."},
        {"q": "What is a 'Test Plan'?", "a": "A test plan is a document that outlines the strategy, objectives, resources, and schedule for a testing project."},
        {"q": "How do you evaluate the quality of a software product?", "a": "Quality is evaluated based on defect density, test coverage, user feedback, and how well it meets business requirements."}
    ],
    'DevOps Engineer': [
        {"q": "What is 'DevOps' and why is it important?", "a": "DevOps is a set of practices that combines development and operations to shorten the development life cycle and provide high-quality software continuously."},
        {"q": "Explain the 'CI/CD' pipeline.", "a": "CI (Continuous Integration) automates code merging and testing. CD (Continuous Deployment) automates the delivery of code to production."},
        {"q": "What is 'Infrastructure as Code' (IaC)?", "a": "IaC allows you to manage and provision infrastructure using machine-readable configuration files (like Terraform or Ansible) instead of manual processes."},
        {"q": "How do you use 'Docker' in DevOps?", "a": "Docker is used to create consistent, lightweight containers that package the application and its environment, ensuring it runs the same way everywhere."},
        {"q": "What is 'Kubernetes' and how does it work?", "a": "Kubernetes is a container orchestration platform that automates the deployment, scaling, and management of containerized applications across a cluster."},
        {"q": "Explain 'Configuration Management'.", "a": "Configuration management involves automating the setup and maintenance of servers and software using tools like Ansible, Chef, or Puppet."},
        {"q": "How do you monitor application performance and logs?", "a": "We use tools like Prometheus, Grafana, and the ELK stack (Elasticsearch, Logstash, Kibana) to collect and visualize metrics and logs."},
        {"q": "What is 'Continuous Monitoring'?", "a": "Continuous monitoring is the process of tracking the health and performance of applications and infrastructure in real-time to detect issues early."},
        {"q": "Explain the concept of 'GitOps'.", "a": "GitOps is a practice where Git is used as the single source of truth for infrastructure and application configurations, with automation to sync changes to the cluster."},
        {"q": "How do you handle security in a DevOps environment?", "a": "Security (DevSecOps) is integrated into the CI/CD pipeline through automated vulnerability scanning, secret management, and compliance checks."},
        {"q": "What is a 'Microservices' architecture from a DevOps perspective?", "a": "DevOps handles the complexity of microservices by automating the deployment and monitoring of many small, independent services communicating via APIs."},
        {"q": "How do you manage cloud resources efficiently?", "a": "Efficient management involves auto-scaling, right-sizing instances, and using cost-monitoring tools to avoid unnecessary expenses."},
        {"q": "What is 'Zero Downtime Deployment'?", "a": "Zero downtime deployment ensures that the application remains available to users while new code is being deployed, usually via blue-green or rolling updates."},
        {"q": "Explain 'Canary Releases' and 'Blue-Green Deployments'.", "a": "Canary releases roll out changes to a small group of users first. Blue-green deployment has two identical environments, one for production and one for the new version."},
        {"q": "How do you handle incident management and disaster recovery?", "a": "We use automated alerting, incident response playbooks, and regular backups to ensure quick recovery from system failures."},
        {"q": "What is 'SRE'?", "a": "Site Reliability Engineering (SRE) is a discipline that applies software engineering principles to operations to create highly reliable and scalable software systems."},
        {"q": "Explain the use of 'Jenkins' or 'GitHub Actions'.", "a": "These are automation servers used to create CI/CD pipelines that build, test, and deploy code automatically whenever changes are pushed to the repository."},
        {"q": "How do you optimize the build and deployment process?", "a": "Optimization involves using parallel builds, caching dependencies, and minimizing the size of container images to speed up the pipeline."},
        {"q": "What is 'Serverless' from a DevOps perspective?", "a": "Serverless reduces operational overhead as the cloud provider manages the infrastructure, allowing DevOps to focus on application logic and monitoring."},
        {"q": "Explain the importance of 'Collaboration' in DevOps.", "a": "Collaboration between development, operations, and security teams is the core of DevOps, breaking down silos to deliver better software faster."}
    ],
    'Database Administrator': [
        {"q": "What are the primary responsibilities of a DBA?", "a": "Responsibilities include database installation, configuration, backup and recovery, performance tuning, and ensuring data security and integrity."},
        {"q": "Explain 'Database Indexing' and its types.", "a": "Indexing speeds up data retrieval. Common types include B-tree indexes, Hash indexes, and Bitmap indexes, each suited for different data types."},
        {"q": "How do you perform a database backup and recovery?", "a": "Backups can be full, incremental, or differential. Recovery involves restoring from these backups and applying transaction logs to return the database to a consistent state."},
        {"q": "What is 'Database Normalization'?", "a": "Normalization is the process of organizing data to reduce redundancy and improve data integrity by dividing tables and defining relationships between them."},
        {"q": "How do you optimize slow-running SQL queries?", "a": "Optimization involves analyzing query execution plans, adding or tuning indexes, avoiding correlated subqueries, and using efficient joins."},
        {"q": "Explain 'Database Security' and user permissions.", "a": "Security involves using strong passwords, restricting user access through roles (RBAC), and using encryption for data at rest and in transit."},
        {"q": "What is 'Database Replication' and 'High Availability'?", "a": "Replication copies data to multiple servers (Master-Slave). High availability ensures the database remains accessible even if one server fails."},
        {"q": "How do you handle database migrations?", "a": "Migrations are version-controlled scripts that update the database schema (adding tables/columns) without losing existing data."},
        {"q": "What is 'Database Monitoring' and what tools do you use?", "a": "Monitoring tracks metrics like CPU usage, disk I/O, and slow queries. Tools include Nagios, Zabbix, or native tools like Oracle Enterprise Manager."},
        {"q": "Explain 'Data Integrity' and 'Constraints'.", "a": "Data integrity ensures accuracy. Constraints like Primary Key, Foreign Key, Unique, and Not Null enforce these rules at the database level."},
        {"q": "What is 'Database Sharding'?", "a": "Sharding is a technique for horizontal scaling where large databases are split into smaller, more manageable pieces called shards across multiple servers."},
        {"q": "How do you manage database storage and performance?", "a": "Storage management involves monitoring disk space, managing data files, and performing regular maintenance like index rebuilding."},
        {"q": "Explain 'ACID' properties.", "a": "ACID (Atomicity, Consistency, Isolation, Durability) ensures that database transactions are processed reliably and accurately even in case of failures."},
        {"q": "What is 'Concurrency Control' in databases?", "a": "Concurrency control ensures that multiple transactions can occur simultaneously without violating data integrity, using techniques like locking and timestamping."},
        {"q": "How do you handle deadlocks?", "a": "A deadlock occurs when two transactions wait for each other to release locks. DBAs handle them by detecting deadlocks and terminating one of the transactions."},
        {"q": "Explain 'Data Warehousing' vs 'OLTP'.", "a": "OLTP is for day-to-day transactions (fast updates). Data Warehousing is for analytical processing (fast retrieval of large amounts of historical data)."},
        {"q": "What is a 'Stored Procedure' and its benefits?", "a": "A stored procedure is a block of code stored in the database. Benefits include improved performance, reduced network traffic, and better security."},
        {"q": "How do you perform database tuning?", "a": "Tuning involves adjusting configuration parameters (like memory allocation), optimizing SQL queries, and improving physical data storage."},
        {"q": "What is 'NoSQL' and when is it used?", "a": "NoSQL is non-relational and flexible. It's used for large-scale, unstructured data like social media posts, real-time data, and big data applications."},
        {"q": "Explain the importance of 'Documentation' for a DBA.", "a": "Documentation is vital for tracking changes, maintenance schedules, backup procedures, and recovery plans to ensure system stability."}
    ],
    'Data Engineer': [
        {"q": "What is a 'Data Pipeline'?", "a": "A data pipeline is a series of automated processes that move data from a source system to a destination system (like a data warehouse) for analysis."},
        {"q": "Explain 'ETL' (Extract, Transform, Load).", "a": "ETL is the process of extracting data from various sources, transforming it into a useful format, and loading it into a final destination like a data warehouse."},
        {"q": "What is the difference between a 'Data Warehouse' and a 'Data Lake'?", "a": "A data warehouse stores structured, processed data. A data lake stores vast amounts of raw data (structured and unstructured) for future processing."},
        {"q": "How do you handle 'Big Data' processing?", "a": "Big data is processed using distributed frameworks like Apache Spark or Hadoop, which split tasks across a cluster of computers to handle massive volumes."},
        {"q": "What are 'Distributed Systems' in the context of data engineering?", "a": "Distributed systems consist of multiple computers working together as one to process large datasets and provide high availability and scalability."},
        {"q": "Explain the use of 'NoSQL' databases for large datasets.", "a": "NoSQL databases like Cassandra or MongoDB provide high scalability and flexible schemas, making them ideal for handling high-velocity, unstructured big data."},
        {"q": "How do you ensure 'Data Quality' and 'Consistency'?", "a": "Quality is ensured through data profiling, validation rules, and automated testing during the ETL process to find and fix errors early."},
        {"q": "What is 'Data Modeling'?", "a": "Data modeling is the process of creating a visual representation of how data is structured, stored, and related in a system, such as using star or snowflake schemas."},
        {"q": "Explain 'Real-time Data Processing'.", "a": "Real-time processing (using Kafka or Flink) handles data as it is generated, allowing for immediate analysis and decision-making for things like fraud detection."},
        {"q": "How do you optimize data storage and retrieval?", "a": "Optimization involves using efficient file formats (Parquet), partitioning data, and choosing the right storage systems (e.g., S3 or Redshift)."},
        {"q": "What is 'Cloud Data Engineering'?", "a": "Cloud data engineering uses cloud-based tools (like AWS Glue or Google BigQuery) to build and manage data pipelines and warehouses more efficiently and at a lower cost."},
        {"q": "Explain the concept of 'Data Governance'.", "a": "Data governance is a framework for managing data availability, usability, integrity, and security within an organization to ensure data is used correctly."},
        {"q": "How do you handle data partitioning and indexing?", "a": "Partitioning splits large tables into smaller pieces based on values (like date) to speed up queries. Indexing creates a map to find data faster."},
        {"q": "What is a 'Schema-on-read' vs 'Schema-on-write'?", "a": "Schema-on-write validates data as it is stored (databases). Schema-on-read applies a schema when the data is fetched (data lakes), allowing more flexibility."},
        {"q": "How do you manage data dependencies in a pipeline?", "a": "Dependencies are managed using workflow orchestration tools like Airflow, which ensure tasks run in the correct order based on their relationships."},
        {"q": "What are the common data file formats?", "a": "Common formats include Parquet (columnar), Avro (row-based), and JSON/CSV for unstructured data. Parquet is highly efficient for analytical queries."},
        {"q": "Explain 'Serverless' data processing.", "a": "Serverless allows data engineers to run processing tasks without managing servers, paying only for the actual computation time (e.g., AWS Glue)."},
        {"q": "How do you monitor and debug data pipelines?", "a": "Monitoring involves tracking task success rates, data volume, and latency using logging and dashboarding tools to detect and fix failures."},
        {"q": "What is 'Data Orchestration'?", "a": "Data orchestration (e.g., Apache Airflow) is the process of automating and managing complex data workflows to ensure data moves through the pipeline correctly."},
        {"q": "Explain the role of 'APIs' in data engineering.", "a": "APIs allow data pipelines to interact with external systems to fetch data from social media, weather services, or internal applications for analysis."}
    ],
    'UI & UX Designer': [
        {"q": "What is the difference between UI and UX design?", "a": "UI (User Interface) is the visual layout (colors, buttons). UX (User Experience) is the overall feel and usability of the product."},
        {"q": "Explain your 'Design Process'.", "a": "My process includes Empathizing with users, Defining the problem, Ideating solutions, Prototyping, and Testing (User-Centered Design)."},
        {"q": "What are the principles of 'Good Design'?", "a": "Good design is aesthetic, intuitive, accessible, consistent, and solves a real problem for the user."},
        {"q": "How do you conduct 'User Research'?", "a": "Research methods include surveys, interviews, usability testing, and analyzing user behavior through analytics tools."},
        {"q": "What is a 'User Persona'?", "a": "A user persona is a fictional character that represents a specific type of user, helping designers understand their needs, goals, and pain points."},
        {"q": "Explain 'Wireframing' vs 'Prototyping'.", "a": "Wireframes are low-fidelity blueprints (skeletons). Prototypes are interactive models that simulate the final product's behavior."},
        {"q": "How do you handle feedback and iteration?", "a": "I treat feedback as a tool for improvement, iterating on designs based on user testing data and stakeholder requirements."},
        {"q": "What is 'Accessibility' in design?", "a": "Accessibility ensures that digital products are usable by everyone, including people with disabilities (e.g., color contrast, screen reader support)."},
        {"q": "Explain 'Visual Hierarchy'.", "a": "Visual hierarchy is the arrangement of elements in a way that implies importance, guiding the user's eye to the most critical information first."},
        {"q": "How do you choose a color palette and typography?", "a": "I choose colors and fonts based on the brand identity, target audience, and the emotional impact I want the product to have."},
        {"q": "What is 'Responsive Design' from a UI perspective?", "a": "Responsive UI adapts its layout, images, and navigation elements to provide an optimal experience across all device screen sizes."},
        {"q": "Explain 'Information Architecture'.", "a": "Information Architecture is the organization and labeling of content to help users find information and complete tasks efficiently."},
        {"q": "How do you design for 'Micro-interactions'?", "a": "Micro-interactions are subtle animations (like a button hover effect) that provide feedback and make the product feel alive and responsive."},
        {"q": "What is 'Usability Testing'?", "a": "Usability testing involves watching real users perform tasks on your product to identify areas of confusion or friction in the design."},
        {"q": "How do you stay up-to-date with design trends?", "a": "I follow design blogs, attend webinars, and study successful products on platforms like Dribbble and Behance."},
        {"q": "Explain the use of 'Design Systems'.", "a": "A design system is a collection of reusable components and standards (UI kit) that ensures consistency and speeds up the design-to-development process."},
        {"q": "How do you collaborate with developers?", "a": "I use handoff tools like Figma, provide clear documentation, and participate in regular check-ins to ensure technical feasibility."},
        {"q": "What are the common design tools you use?", "a": "My primary tools are Figma for design/prototyping, Adobe Creative Cloud for assets, and Miro for user journey mapping."},
        {"q": "Explain 'User Journey Mapping'.", "a": "A user journey map is a visual timeline of a user's interaction with a product, highlighting their actions, emotions, and pain points throughout the process."},
        {"q": "How do you measure the success of a design?", "a": "Success is measured using metrics like task completion rate, time on task, user satisfaction scores (NPS), and conversion rates."}
    ],
    'Product Manager': [
        {"q": "What is the role of a Product Manager?", "a": "A PM sits at the intersection of business, technology, and user experience, leading the strategy and delivery of a successful product."},
        {"q": "How do you define a 'Product Vision' and 'Strategy'?", "a": "Vision is the long-term 'why'. Strategy is the plan for how to achieve that vision while meeting business goals and user needs."},
        {"q": "How do you prioritize features for a product roadmap?", "a": "I use frameworks like RICE (Reach, Impact, Confidence, Effort) or MoSCoW to prioritize features based on value and feasibility."},
        {"q": "What is an 'MVP'?", "a": "A Minimum Viable Product is the simplest version of a product that can be released to early users to gather feedback and validate core assumptions."},
        {"q": "How do you conduct 'Market Research'?", "a": "Research involves analyzing competitor products, studying industry trends, and understanding customer pain points through direct interviews and surveys."},
        {"q": "Explain 'User-Centric Design' from a PM perspective.", "a": "It means starting with the user's problem and ensuring every product decision is validated against actual user needs and behavior."},
        {"q": "How do you measure product success (KPIs)?", "a": "Key Performance Indicators include Monthly Active Users (MAU), Customer Acquisition Cost (CAC), Churn Rate, and Revenue growth."},
        {"q": "Explain 'Agile' and 'Scrum' in product management.", "a": "Agile is a flexible, iterative approach to development. Scrum is a specific Agile framework using sprints, stand-ups, and backlogs to deliver value quickly."},
        {"q": "How do you handle competing stakeholder interests?", "a": "I use data-driven evidence and the product vision to align stakeholders and make objective decisions that benefit the product as a whole."},
        {"q": "What is 'Product-Market Fit'?", "a": "Product-market fit is achieved when a product successfully satisfies a strong market demand with a large enough customer base to sustain growth."},
        {"q": "How do you perform 'Competitor Analysis'?", "a": "Analysis involves comparing features, pricing, target audiences, and SWOT (Strengths, Weaknesses, Opportunities, Threats) for rival products."},
        {"q": "Explain the 'Product Life Cycle'.", "a": "The life cycle stages are Introduction, Growth, Maturity, and Decline. PM strategies change depending on which stage the product is in."},
        {"q": "How do you gather and use customer feedback?", "a": "I use feedback from support tickets, reviews, and direct interviews to identify feature gaps and usability issues for future roadmap planning."},
        {"q": "What is 'GTM' strategy?", "a": "A Go-To-Market strategy is a plan for launching a new product, covering target audience, pricing, distribution channels, and marketing tactics."},
        {"q": "How do you manage product risk?", "a": "Risk management involves identifying technical, market, and business risks early and creating mitigation plans to address them."},
        {"q": "Explain the role of 'Data' in product decisions.", "a": "Data allows PMs to make objective decisions, validate hypotheses through A/B testing, and track how users actually interact with the product."},
        {"q": "How do you collaborate with engineering and design teams?", "a": "I provide clear requirements (PRDs), participate in stand-ups, and act as the bridge between technical constraints and user needs."},
        {"q": "What is 'Product Discovery'?", "a": "Product discovery is the process of deciding what to build by validating ideas quickly through prototyping and user testing before full-scale development."},
        {"q": "How do you handle a product failure?", "a": "I perform a post-mortem to understand why it failed, gather lessons learned, and use those insights to pivot or improve future products."},
        {"q": "What is your approach to 'Stakeholder Management'?", "a": "My approach is built on transparency, regular communication, and setting clear expectations to ensure everyone is aligned with the product goals."}
    ],
    'Business Analyst (BA)': [
        {"q": "What are the key responsibilities of a Business Analyst?", "a": "BAs analyze business needs, bridge the gap between stakeholders and technology teams, and document requirements for project success."},
        {"q": "How do you gather and document 'Requirements'?", "a": "Requirements are gathered through interviews and workshops and documented using Business Requirement Documents (BRD) or User Stories."},
        {"q": "What is the difference between 'Functional' and 'Non-functional' requirements?", "a": "Functional: WHAT the system does (e.g., 'user can login'). Non-functional: HOW the system performs (e.g., 'system should load in 2 seconds')."},
        {"q": "Explain 'Stakeholder Analysis'.", "a": "Analysis involves identifying everyone involved in a project and understanding their influence, interests, and how the project affects them."},
        {"q": "How do you conduct a 'Gap Analysis'?", "a": "Gap analysis compares the current state ('As-Is') with the desired future state ('To-Be') to identify what is needed to reach the goal."},
        {"q": "What is a 'Use Case'?", "a": "A use case describes a specific interaction between a user (actor) and the system to achieve a particular goal."},
        {"q": "Explain 'BPMN'?", "a": "Business Process Model and Notation (BPMN) is a standard visual representation for business processes, using flowcharts to show workflows and interactions."},
        {"q": "How do you handle changes in requirements?", "a": "Changes are handled through a formal change control process, assessing the impact on scope, budget, and timeline before approval."},
        {"q": "What is a 'User Story' in Agile?", "a": "A user story is a simple explanation of a feature from the user's perspective, usually following the format: 'As a [user], I want [action] so that [benefit].'"},
        {"q": "Explain 'Cost-Benefit Analysis'.", "a": "It's the process of comparing the expected costs of a project with its potential benefits to determine its financial feasibility and ROI."},
        {"q": "How do you facilitate meetings and workshops?", "a": "I set clear agendas, encourage participation, manage conflict, and ensure that all key decisions and action items are documented."},
        {"q": "What is 'Data Analysis' in the context of a BA role?", "a": "BAs use data analysis (often with SQL or Excel) to identify trends, validate requirements, and provide data-driven recommendations to the business."},
        {"q": "How do you bridge the gap between business and technology?", "a": "I translate complex business needs into clear technical specifications that developers can understand and implement correctly."},
        {"q": "Explain 'SWOT Analysis'.", "a": "SWOT identifies Strengths, Weaknesses, Opportunities, and Threats for a business or project to guide strategic decision-making."},
        {"q": "What is 'Acceptance Criteria'?", "a": "Acceptance criteria are a set of conditions that a feature must meet for it to be accepted as complete by the customer or stakeholder."},
        {"q": "How do you verify and validate requirements?", "a": "Verification ensures the requirements are well-written. Validation ensures they actually meet the needs of the business and the users."},
        {"q": "Explain 'Feasibility Study'.", "a": "A feasibility study assesses the technical, financial, and operational viability of a project before a full commitment is made."},
        {"q": "How do you use 'SQL' or 'Excel' for business analysis?", "a": "I use SQL to query databases for raw data and Excel for data cleaning, modeling, and creating reports and visualizations."},
        {"q": "What is 'Process Improvement'?", "a": "Process improvement is the practice of analyzing existing business processes to identify inefficiencies and implement changes to improve speed, quality, or cost."},
        {"q": "How do you manage project scope?", "a": "Scope management involves clearly defining what is IN and OUT of a project and using a scope statement to prevent 'scope creep' during development."}
    ],
    'IT Support / Help Desk': [
        {"q": "How do you handle a frustrated or difficult customer?", "a": "I remain calm, listen actively, empathize with their problem, and focus on providing a clear solution while maintaining professional communication."},
        {"q": "Explain the process of troubleshooting a hardware issue.", "a": "Troubleshooting involves identifying the symptom, isolating the faulty component, testing solutions, and documenting the fix for future reference."},
        {"q": "How do you diagnose and resolve software problems?", "a": "Diagnosis involves checking error logs, replicating the issue, identifying conflicts, and applying patches or re-installing the software if needed."},
        {"q": "What is 'Remote Support'?", "a": "Remote support allows IT to access and troubleshoot a user's computer over the internet using tools like TeamViewer or AnyDesk to fix issues without being physically present."},
        {"q": "Explain 'Ticketing Systems'?", "a": "Ticketing systems (like Jira or ServiceNow) are used to track, prioritize, and manage user support requests throughout their entire life cycle."},
        {"q": "How do you handle network connectivity issues?", "a": "Connectivity issues are handled by checking cables, restarting routers/modems, verifying IP settings, and testing network hardware components."},
        {"q": "What is 'Active Directory'?", "a": "Active Directory is a Microsoft service used to manage users, computers, and permissions within a network, allowing for centralized administration and security."},
        {"q": "Explain the importance of 'Documentation' in IT support.", "a": "Documentation creates a knowledge base of known issues and solutions, allowing the support team to resolve common problems faster and more consistently."},
        {"q": "How do you prioritize multiple support requests?", "a": "Priority is based on the severity of the issue (e.g., system-wide outage vs individual software bug) and the impact on business operations."},
        {"q": "What is 'Operating System' installation and configuration?", "a": "It involves installing the OS (Windows/Linux/macOS), setting up user accounts, installing drivers, and configuring security settings for the user."},
        {"q": "Explain 'Email Setup' and troubleshooting.", "a": "Setup involves configuring SMTP/IMAP settings. Troubleshooting includes checking server status, verifying credentials, and fixing sync or delivery issues."},
        {"q": "How do you handle virus and malware removal?", "a": "Removal involves running full scans with antivirus software, isolating the device from the network, and sometimes performing a clean OS install if necessary."},
        {"q": "What is 'Data Backup' and 'Restoration' for end users?", "a": "Backup involves copying important files to external drives or cloud storage. Restoration is the process of getting those files back if the original data is lost."},
        {"q": "Explain 'Printer Setup' and troubleshooting.", "a": "Setup involves installing drivers and connecting the printer to the network. Troubleshooting includes clearing jams, checking ink levels, and fixing connectivity errors."},
        {"q": "How do you stay updated with the latest technology trends?", "a": "I follow IT blogs, participate in online forums, and take certification courses (like CompTIA A+ or Network+) to keep my skills fresh."},
        {"q": "What is 'ITIL'?", "a": "ITIL (Information Technology Infrastructure Library) is a set of best practices for IT service management (ITSM) that helps align IT services with business needs."},
        {"q": "How do you educate users on basic IT security?", "a": "I provide tips on creating strong passwords, identifying phishing emails, and the importance of keeping software and antivirus updated."},
        {"q": "What is 'Mobile Device Management'?", "a": "MDM allows IT to manage, secure, and monitor mobile devices (phones/tablets) used by employees to ensure they follow company security policies."},
        {"q": "How do you handle a system-wide outage?", "a": "Outages are handled by immediately notifying management, investigating the root cause, working to restore services, and keeping users updated on the progress."},
        {"q": "Explain the importance of 'Communication Skills' for IT support.", "a": "Good communication ensures that users understand the problem and the solution, building trust and reducing frustration during stressful technical issues."}
    ],
    'HR (Human Resources)': [
        {"q": "What are the core functions of Human Resources?", "a": "Core functions include Recruitment, Employee Relations, Performance Management, Training and Development, and Compensation and Benefits."},
        {"q": "Explain the 'Recruitment and Selection' process.", "a": "The process involves job posting, screening resumes, conducting interviews, performing background checks, and extending job offers to the best candidates."},
        {"q": "How do you handle 'Employee Relations' and conflict resolution?", "a": "I act as a neutral mediator, listening to all sides, investigating the issue fairly, and working to find a resolution that follows company policy."},
        {"q": "What is 'Performance Management'?", "a": "Performance management is a continuous process of setting goals, reviewing progress, and providing feedback to help employees achieve their best results."},
        {"q": "Explain 'Employee Onboarding' and its importance.", "a": "Onboarding is the process of integrating new hires into the company, helping them understand their role, the culture, and the tools they need to succeed."},
        {"q": "How do you manage 'Training and Development' programs?", "a": "I identify skill gaps in the workforce and organize workshops, online courses, and mentorship programs to help employees grow professionally."},
        {"q": "What is 'Compensation and Benefits'?", "a": "This involves managing salary structures, bonuses, health insurance, retirement plans, and other perks that attract and retain talented employees."},
        {"q": "Explain 'HR Compliance' and legal requirements.", "a": "HR compliance ensures that the company follows all labor laws regarding fair pay, safety, non-discrimination, and employee rights."},
        {"q": "How do you foster a positive 'Company Culture'?", "a": "Culture is built by promoting core values, encouraging open communication, recognizing achievements, and organizing team-building activities."},
        {"q": "What is 'Employee Engagement' and how do you measure it?", "a": "Engagement is how committed employees are to their work. It's measured using surveys, retention rates, and feedback sessions."},
        {"q": "How do you handle 'Disciplinary Actions' and terminations?", "a": "I follow a progressive disciplinary process, documenting all issues fairly, and handling terminations with professionalism, respect, and legal compliance."},
        {"q": "What is 'DEI' in HR?", "a": "Diversity, Equity, and Inclusion (DEI) involves creating a workplace that values different backgrounds and ensures everyone has equal opportunities and feels included."},
        {"q": "Explain 'Succession Planning'.", "a": "Succession planning is the process of identifying and developing internal talent to fill key leadership roles when they become vacant in the future."},
        {"q": "How do you manage 'HR Data' and analytics?", "a": "I use HRIS (HR Information Systems) to track data like turnover rates and hiring costs, using those insights to improve HR strategies."},
        {"q": "What is 'Change Management' from an HR perspective?", "a": "Change management involves helping employees adapt to major shifts in the company, such as mergers or new technology, through clear communication and support."},
        {"q": "How do you handle 'Workplace Health and Safety'?", "a": "I ensure that the company follows safety regulations, conducts regular inspections, and provides training to prevent accidents and protect employee well-being."},
        {"q": "Explain 'Strategic HR Planning'.", "a": "Strategic planning involves aligning HR goals (like talent acquisition) with the long-term business objectives of the company to ensure future success."},
        {"q": "How do you conduct an 'Exit Interview'?", "a": "Exit interviews are conducted with departing employees to gather feedback on their experience and identify areas where the company can improve."},
        {"q": "What is 'Employer Branding'?", "a": "Employer branding is the process of promoting the company as a great place to work to attract high-quality candidates in a competitive job market."},
        {"q": "How do you maintain 'Employee Confidentiality'?", "a": "Confidentiality is maintained by strictly controlling access to employee records and ensuring that sensitive personal information is never shared without authorization."}
    ],
    'Project Manager': [
        {"q": "What are the key phases of the 'Project Management Life Cycle'?", "a": "The phases are Initiation, Planning, Execution, Monitoring and Control, and Project Closure."},
        {"q": "Explain 'Agile' vs 'Waterfall' methodologies.", "a": "Agile is iterative and flexible (best for changing requirements). Waterfall is linear and sequential (best for fixed-scope, well-defined projects)."},
        {"q": "How do you define 'Project Scope' and manage scope creep?", "a": "Scope is defined using a scope statement. Scope creep is managed by a formal change control process to evaluate any additions to the project."},
        {"q": "How do you create a 'Project Schedule'?", "a": "Schedules are created using tools like Gantt charts to map out tasks, durations, and dependencies (critical path) to meet the project deadline."},
        {"q": "Explain 'Risk Management' in projects.", "a": "Risk management involves identifying potential problems early, assessing their impact, and creating mitigation plans to minimize their effect on the project."},
        {"q": "How do you manage 'Project Budgets' and resources?", "a": "I track all expenses against the budget and allocate human and material resources efficiently to ensure the project stays within financial limits."},
        {"q": "What is 'Stakeholder Communication' and why is it important?", "a": "Regular communication keeps everyone informed of progress and issues, ensuring that the project meets the expectations of all interested parties."},
        {"q": "How do you handle 'Project Conflicts' and roadblocks?", "a": "I identify the root cause of the conflict, facilitate discussions to find a solution, and remove any obstacles that are preventing the team from progressing."},
        {"q": "What is 'Quality Management' in projects?", "a": "Quality management ensures that the project deliverables meet the required standards and user needs through regular inspections and testing."},
        {"q": "Explain 'Change Control' processes.", "a": "Change control is a formal process for requesting, evaluating, and approving changes to the project scope, timeline, or budget to maintain control."},
        {"q": "How do you measure 'Project Success'?", "a": "Success is measured by meeting the project objectives on time, within budget, and to the satisfaction of the stakeholders and end users."},
        {"q": "What is 'Scrum' and the role of a 'Scrum Master'?", "a": "Scrum is an Agile framework. The Scrum Master facilitates the process, removes blockers, and ensures the team follows Scrum principles to deliver value."},
        {"q": "How do you lead and motivate a project team?", "a": "I set clear goals, provide support, recognize achievements, and foster a collaborative environment where every team member feels valued."},
        {"q": "Explain the use of 'Project Management Tools'.", "a": "Tools like Jira, Trello, and MS Project help track tasks, manage timelines, and facilitate team collaboration throughout the project."},
        {"q": "What is 'Procurement Management'?", "a": "Procurement involves identifying what goods or services need to be purchased from outside vendors and managing those contracts and relationships."},
        {"q": "How do you handle a project that is behind schedule?", "a": "I analyze the causes of the delay, re-prioritize tasks, and potentially allocate more resources (crashing) to get the project back on track."},
        {"q": "Explain 'Lessons Learned' and project closure.", "a": "Closure involves finalizing all tasks, releasing resources, and documenting 'lessons learned' to improve the performance of future projects."},
        {"q": "What is 'Strategic Alignment' in project management?", "a": "Alignment ensures that every project supports the overall business goals and long-term vision of the organization."},
        {"q": "How do you manage 'Virtual Teams'?", "a": "Virtual teams are managed through clear communication, using collaboration tools for video calls and task tracking, and setting clear expectations for remote work."},
        {"q": "Explain the 'Triple Constraint' in project management.", "a": "The triple constraint (or project triangle) consists of Scope, Time, and Cost. Changing one will inevitably impact the others."}
    ]
}
