# Generated by Django 5.2.14 on 2026-06-03 05:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('interview', '0002_interviewsession_extracted_skills_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='interviewsession',
            name='experience_level',
            field=models.CharField(default='Fresher', max_length=50),
        ),
    ]
