# Generated by Django 5.2.14 on 2026-05-16 11:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_badge_user_is_premium_userbadge'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='ai_difficulty',
            field=models.CharField(default='Beginner', max_length=20),
        ),
        migrations.AddField(
            model_name='user',
            name='ai_personality',
            field=models.CharField(default='Friendly Teacher', max_length=50),
        ),
        migrations.AddField(
            model_name='user',
            name='ai_voice',
            field=models.CharField(default='Female - American', max_length=50),
        ),
        migrations.AddField(
            model_name='user',
            name='app_theme',
            field=models.CharField(default='Dark Neon', max_length=50),
        ),
        migrations.AddField(
            model_name='user',
            name='notifications_enabled',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='user',
            name='preferred_language',
            field=models.CharField(default='English', max_length=20),
        ),
        migrations.AddField(
            model_name='user',
            name='privacy_visible',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='user',
            name='speaking_speed',
            field=models.FloatField(default=1.0),
        ),
    ]
